// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using garbageDetetionApi.Context;

#nullable disable

namespace garbageDetetionApi.Migrations
{
    [DbContext(typeof(GarbageDbContext))]
    [Migration("20250605215345_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("garbageDetetionApi.Models.Garbage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("CameraId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Confidence_score")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Detected")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Humidity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Temp")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("Weather")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Windspeed")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Garbages", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CameraId = new Guid("d3c1f8b2-4e5f-4a2b-9c3e-8f1b2c3d4e5f"),
                            Confidence_score = 0.95m,
                            Detected = "Plastic Bottle",
                            Humidity = 45.0m,
                            Latitude = 51.591415m,
                            Longitude = 4.778720m,
                            Temp = 22.5m,
                            Timestamp = new DateTime(2025, 5, 15, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            Weather = "Sunny",
                            Windspeed = 5.2m
                        },
                        new
                        {
                            Id = 2,
                            CameraId = new Guid("d3c1f8b2-4e5f-4a2b-9c3e-8f1b2c3d4e5f"),
                            Confidence_score = 0.89m,
                            Detected = "Can",
                            Humidity = 55.0m,
                            Latitude = 51.591415m,
                            Longitude = 4.778720m,
                            Temp = 18.3m,
                            Timestamp = new DateTime(2025, 5, 15, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Weather = "Cloudy",
                            Windspeed = 3.8m
                        },
                        new
                        {
                            Id = 3,
                            CameraId = new Guid("d3c1f8b2-4e5f-4a2b-9c3e-8f1b2c3d4e5f"),
                            Confidence_score = 0.92m,
                            Detected = "Paper",
                            Humidity = 80.0m,
                            Latitude = 51.591415m,
                            Longitude = 4.778720m,
                            Temp = 16.0m,
                            Timestamp = new DateTime(2025, 5, 15, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            Weather = "Rainy",
                            Windspeed = 7.1m
                        },
                        new
                        {
                            Id = 4,
                            CameraId = new Guid("d3c1f8b2-4e5f-4a2b-9c3e-8f1b2c3d4e5f"),
                            Confidence_score = 0.88m,
                            Detected = "Glass",
                            Humidity = 50.0m,
                            Latitude = 51.591415m,
                            Longitude = 4.778720m,
                            Temp = 20.0m,
                            Timestamp = new DateTime(2025, 5, 15, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Weather = "Windy",
                            Windspeed = 12.0m
                        },
                        new
                        {
                            Id = 5,
                            CameraId = new Guid("d3c1f8b2-4e5f-4a2b-9c3e-8f1b2c3d4e5f"),
                            Confidence_score = 0.90m,
                            Detected = "Food Wrapper",
                            Humidity = 40.0m,
                            Latitude = 51.591415m,
                            Longitude = 4.778720m,
                            Temp = 24.0m,
                            Timestamp = new DateTime(2025, 5, 15, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            Weather = "Sunny",
                            Windspeed = 4.5m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
