name: Trigger auto deployment for garbagecontainer

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/garbagecontainer-AutoDeployTrigger-6ed77638-fd14-44cc-b35c-799585b33bc7.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.GARBAGECONTAINER_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.GARBAGECONTAINER_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.GARBAGECONTAINER_AZURE_SUBSCRIPTION_ID }}

      - name: Run unit tests
        run: |
          dotnet test ./UnitTests/UnitTests.csproj --no-build --verbosity normal
          
      - name: Setup .Net Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'
      
      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: garbageDetetionApi
          dockerfilePath: Dockerfile
          registryUrl: garbageregistry.azurecr.io
          registryUsername: ${{ secrets.GARBAGECONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.GARBAGECONTAINER_REGISTRY_PASSWORD }}
          containerAppName: garbagecontainer
          resourceGroup: garbageApi
          imageToBuild: garbageregistry.azurecr.io/garbagecontainer:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_
            
      - name: Run EF
        env:
          DATABASE_CONN_STRING: ${{ secrets.DATABASE_CONN_STRING }}
        run: |
          dotnet tool install --global dotnet-ef
          dotnet tool restore
          dotnet ef database update -p ./garbageDetetionApi/garbageDetetionApi.csproj --connection "$DATABASE_CONN_STRING"



